version: "3.9"

networks:
  founderlink-internal:
  proxy-net:
    external: true

volumes:
  auth-db-data:
  user-db-data:
  startup-db-data:
  investment-db-data:
  team-db-data:
  messaging-db-data:
  notification-db-data:
  payment-db-data:
  wallet-db-data:
  redis-data:
  rabbitmq-data:

services:

  auth-db:
    image: mysql:8.0
    init: true
    container_name: auth-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: auth_service_db
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - auth-db-data:/var/lib/mysql
    networks:
      - founderlink-internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  user-db:
    image: mysql:8.0
    init: true
    container_name: user-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: user_db
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - user-db-data:/var/lib/mysql
    networks:
      - founderlink-internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  startup-db:
    image: mysql:8.0
    init: true
    container_name: startup-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: startup_db
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - startup-db-data:/var/lib/mysql
    networks:
      - founderlink-internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  investment-db:
    image: mysql:8.0
    init: true
    container_name: investment-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: investment_db
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - investment-db-data:/var/lib/mysql
    networks:
      - founderlink-internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  team-db:
    image: mysql:8.0
    init: true
    container_name: team-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: team_db
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - team-db-data:/var/lib/mysql
    networks:
      - founderlink-internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  messaging-db:
    image: mysql:8.0
    init: true
    container_name: messaging-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: messaging_db
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - messaging-db-data:/var/lib/mysql
    networks:
      - founderlink-internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  notification-db:
    image: mysql:8.0
    init: true
    container_name: notification-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: notification_db
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - notification-db-data:/var/lib/mysql
    networks:
      - founderlink-internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  payment-db:
    image: mysql:8.0
    init: true
    container_name: payment-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: payment_db
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - payment-db-data:/var/lib/mysql
    networks:
      - founderlink-internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  wallet-db:
    image: mysql:8.0
    init: true
    container_name: wallet-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: wallet_db
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - wallet-db-data:/var/lib/mysql
    networks:
      - founderlink-internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

   # ================= CORE INFRA ================= #

  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - redis-data:/data
    networks:
      - founderlink-internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - founderlink-internal
    restart: unless-stopped

  # ================= OBSERVABILITY ================= #

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    networks:
      - founderlink-internal
      - proxy-net
    expose:
      - "9411"
    restart: unless-stopped

  # ================= DISCOVERY ================= #

  eureka-server:
    image: ${ACR_LOGIN_SERVER}/eureka-server:${TAG}
    container_name: eureka-server
    networks:
      - founderlink-internal
      - proxy-net
    expose:
      - "8761"
    depends_on:
      - redis
    restart: unless-stopped

  config-server:
    image: ${ACR_LOGIN_SERVER}/config-server:${TAG}
    container_name: config-server
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka
    networks:
      - founderlink-internal
    expose:
      - "8888"
    depends_on:
      - eureka-server
    restart: unless-stopped