server:
  port: 8085

spring:
  application:
    name: team-service
#  config:
#    import: optional:configserver:http://config-server:8888
#  datasource:
#     url: jdbc:mysql://localhost:3306/team_db
#     username: root
#     password: Anim@4748
#     driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate:
#         format_sql: true
#         dialect: org.hibernate.dialect.MySQLDialect
#
#  rabbitmq:
#     host: localhost
#     port: 5672
#     username: guest
#     password: guest
#
#  cloud:
#     openfeign:
#       circuitbreaker:
#         enabled: true
#
#eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
#     register-with-eureka: true
#     fetch-registry: true
#
#management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info
#   endpoint:
#     health:
#       show-details: always
#   tracing:
#     sampling:
#       probability: 1.0
#   zipkin:
#     tracing:
#       endpoint: http://localhost:9411/api/v2/spans
#
#resilience4j:
#   circuitbreaker:
#     instances:
#       startup-service:
#         sliding-window-size: 10
#         failure-rate-threshold: 50
#         wait-duration-in-open-state: 10s
#
#logging:
#   level:
#     root: INFO
#     com.founderlink.team: DEBUG
#   file:
#     name: logs/team-service.log

# ==========================================
# RABBITMQ QUEUES AND EXCHANGES
# ==========================================
#rabbitmq:
#   exchange: founderlink.exchange
#   team:
#     queue: team.queue
#     routing-key: team.invite.sent
#   startup:
#     deleted:
#       queue: team.startup.deleted.queue
#       routing-key: startup.deleted

