# ==========================================
# APPLICATION
# ==========================================

server.port=8084
spring.application.name=investment-service

# ==========================================
# MYSQL DATABASE
# ==========================================

spring.datasource.url=jdbc:mysql://localhost:3306/investment_db
spring.datasource.username=root
spring.datasource.password=parth123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ==========================================
# EUREKA CLIENT
# ==========================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
#eureka.instance.prefer-ip-address=true

# ==========================================
# RABBITMQ
# ==========================================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ==========================================
# ACTUATOR
# ==========================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


# Feign Client
spring.cloud.openfeign.circuitbreaker.enabled=true

# Resilience4j
# Change STARTUP-SERVICE to startup-service
resilience4j.circuitbreaker.instances.startup-service.sliding-window-size=10
resilience4j.circuitbreaker.instances.startup-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.startup-service.wait-duration-in-open-state=10s

logging.level.root=INFO
logging.level.com.founderlink.investment=DEBUG
logging.file.name=logs/investment-service.log