spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/kalyanappari/FounderLink_System_Config

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka