sonar.projectKey=kalyanappari_founderlink-frontend
sonar.organization=kalyanappari
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/test.ts,**/environments/**,**/main.ts,**/assets/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.typescript.lcov.reportPaths=coverage/founderlink-frontend/lcov.info
sonar.javascript.lcov.reportPaths=coverage/founderlink-frontend/lcov.info

sonar.sourceEncoding=UTF-8
